on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          cp ${GITHUB_WORKSPACE}/platform.txt.patch $HOME

      - uses: actions/checkout@v4
        with:
          repository: arduino/arduino-cli
          ref: fix_user_agent_regression

      - uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - run: |
          task build

      - run: |
          ./arduino-cli core install --additional-urls https://www.pjrc.com/teensy/package_teensy_index.json teensy:avr
          ./arduino-cli sketch new "${{ runner.temp }}/Foo"

          #      - run: |
          #export GOPATH=$HOME/go
          #go install go.bug.st/cmdlineprinter@master
          #cp $GOPATH/bin/cmdlineprinter $HOME/.arduino15/packages/teensy/tools/teensy-tools/1.59.0/

          #      - run: |
          #cp $HOME/platform.txt.patch $HOME/.arduino15/packages/teensy/hardware/avr/1.59.0/platform.txt

          #      - name: Setup upterm session
          #uses: lhotari/action-upterm@v1

      - run: |
          ./arduino-cli compile --fqbn teensy:avr:teensy36 "${{ runner.temp }}/Foo" -v

